name: Update README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Add recent activities
        uses: BunnyTheLifeguard/recent-activity@feat/split-pr-events
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
